(function(g){var window=this;'use strict';var gYz=function(Y){Y.publish("autonavvisibility")},AJ0=function(Y,e){Y.O4("onAutonavCoundownStarted",e)},vYU=function(Y){var e,K,x;
return Y==null?void 0:(e=Y.playerOverlays)==null?void 0:(K=e.playerOverlayRenderer)==null?void 0:(x=K.autoplay)==null?void 0:x.playerOverlayAutoplayRenderer},OR=function(Y){var e=Y.D(),K=e.Y;
g.d.call(this,{N:"a",j:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:K?e.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},G:[{N:"div",v2:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},G:[{N:"div",V:{"aria-label":"{{timestamp}}"},v2:["ytp-autonav-timestamp"],Qq:"{{duration}}"},{N:"div",v2:["ytp-autonav-live-stamp"],Qq:"Live"},{N:"div",
v2:["ytp-autonav-upcoming-stamp"],Qq:"Upcoming"},{N:"div",j:"ytp-autonav-list-overlay",G:[{N:"div",j:"ytp-autonav-mix-text",Qq:"Mix"},{N:"div",j:"ytp-autonav-mix-icon"}]}]},{N:"div",v2:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Qq:"{{title}}"},{N:"div",v2:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Qq:"{{author}}"},{N:"div",v2:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Qq:"{{views_and_publish_time}}"}]});this.W=Y;this.suggestion=
null;this.K=K;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},TL=function(Y,e){e=e===void 0?!1:e;
g.d.call(this,{N:"div",j:"ytp-autonav-endscreen-countdown-overlay"});var K=this;this.T=e;this.cancelCommand=this.U=void 0;this.X=0;this.container=new g.d({N:"div",j:"ytp-autonav-endscreen-countdown-container"});g.S(this,this.container);this.container.Ri(this.element);e=Y.D();var x=e.Y;this.W=Y;this.suggestion=null;this.onVideoDataChange("newdata",this.W.getVideoData());this.J(Y,"videodatachange",this.onVideoDataChange);this.K=new g.d({N:"div",j:"ytp-autonav-endscreen-upnext-container",V:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},G:[{N:"div",j:"ytp-autonav-endscreen-upnext-header"},{N:"div",j:"ytp-autonav-endscreen-upnext-alternative-header",Qq:"{{autoplayAlternativeHeader}}"},{N:"a",j:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:x?e.C:""},G:[{N:"div",j:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},G:[{N:"div",V:{"aria-label":"{{timestamp}}"},v2:["ytp-autonav-timestamp"],
Qq:"{{duration}}"},{N:"div",v2:["ytp-autonav-live-stamp"],Qq:"Live"},{N:"div",v2:["ytp-autonav-upcoming-stamp"],Qq:"Upcoming"}]},{N:"div",j:"ytp-autonav-endscreen-video-info",G:[{N:"div",j:"ytp-autonav-endscreen-premium-badge"},{N:"div",j:"ytp-autonav-endscreen-upnext-title",Qq:"{{title}}"},{N:"div",j:"ytp-autonav-endscreen-upnext-author",Qq:"{{author}}"},{N:"div",j:"ytp-autonav-view-and-date",Qq:"{{views_and_publish_time}}"},{N:"div",j:"ytp-autonav-author-and-view",Qq:"{{author_and_views}}"}]}]}]});
g.S(this,this.K);this.K.Ri(this.container.element);x||this.J(this.K.w7("ytp-autonav-endscreen-link-container"),"click",this.Wz);this.W.createClientVe(this.container.element,this,115127);this.W.createClientVe(this.K.w7("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.d({N:"div",j:"ytp-autonav-overlay"});g.S(this,this.overlay);this.overlay.Ri(this.container.element);this.L=new g.d({N:"div",j:"ytp-autonav-endscreen-button-container"});g.S(this,this.L);this.L.Ri(this.container.element);
this.cancelButton=new g.d({N:"button",v2:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",e.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{"aria-label":"Cancel auto-play"},Qq:"Cancel"});g.S(this,this.cancelButton);this.cancelButton.Ri(this.L.element);this.cancelButton.listen("click",this.Ut,this);this.W.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.d({N:"a",v2:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
e.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{href:"{{url}}",role:"button","aria-label":"Play next video"},Qq:"Play now"});g.S(this,this.playButton);this.playButton.Ri(this.L.element);this.playButton.listen("click",this.Wz,this);this.W.createServerVe(this.playButton.element,this.playButton,!0);(e=this.W.getVideoData())&&rJP(this,e);this.Y=new g.S2(function(){juZ(K)},500);
g.S(this,this.Y);this.fm();this.J(Y,"autonavvisibility",this.fm);this.W.Z("web_autonav_color_transition")&&(this.J(Y,"autonavchange",this.WB),this.J(Y,"onAutonavCoundownStarted",this.u6R))},F7=function(Y){var e=Y.W.ph(!0,Y.W.isFullscreen());
g.s$(Y.container.element,"ytp-autonav-endscreen-small-mode",Y.s5(e));g.s$(Y.container.element,"ytp-autonav-endscreen-is-premium",!!Y.suggestion&&!!Y.suggestion.Lki);g.s$(Y.W.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!Y.W.LX());g.s$(Y.W.getRootNode(),"countdown-running",Y.Yo());g.s$(Y.container.element,"ytp-player-content",Y.W.LX());g.ln(Y.overlay.element,{width:e.width+"px"});if(!Y.Yo()){Y.W.LX()?iZM(Y,Math.round(JJq(Y)/1E3)):iZM(Y);e=!!Y.suggestion&&!!Y.suggestion.VG;var K=Y.W.LX()||
!e;g.s$(Y.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!K&&e);g.s$(Y.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",K&&!e);Y.L.iP(Y.W.LX());g.s$(Y.element,"ytp-enable-w2w-color-transitions",Sca(Y))}},juZ=function(Y){var e=JJq(Y),K=Math,x=K.min;
var z=Y.X?Date.now()-Y.X:0;K=x.call(K,z,e);iZM(Y,Math.ceil((e-K)/1E3));e-K<=500&&Y.Yo()?Y.select(!0):Y.Yo()&&Y.Y.start()},JJq=function(Y){if(Y.W.isFullscreen()){var e;
Y=(e=Y.W.getVideoData())==null?void 0:e.H5;return Y===-1||Y===void 0?8E3:Y}return Y.W.LV()>=0?Y.W.LV():g.ta(Y.W.D().experiments,"autoplay_time")||1E4},rJP=function(Y,e){e=e.getWatchNextResponse();
var K,x;e=(K=vYU(e))==null?void 0:(x=K.nextButton)==null?void 0:x.buttonRenderer;Y.U=e==null?void 0:e.navigationEndpoint;K=e==null?void 0:e.trackingParams;Y.playButton&&K&&Y.W.setTrackingParams(Y.playButton.element,K)},Sca=function(Y){var e;
return!((e=Y.W.getVideoData())==null||!e.watchToWatchTransitionRenderer)},iZM=function(Y,e){e=e===void 0?-1:e;
Y=Y.K.w7("ytp-autonav-endscreen-upnext-header");g.Ly(Y);if(e>=0){e=String(e);var K="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],x="Up next in $SECONDS".indexOf(K);if(x>=0){Y.appendChild(g.GR("Up next in $SECONDS".slice(0,x)));var z=g.ob("span");g.DC(z,"ytp-autonav-endscreen-upnext-header-countdown-number");g.X2(z,e);Y.appendChild(z);Y.appendChild(g.GR("Up next in $SECONDS".slice(x+K.length)));return}}g.X2(Y,"Up next")},ER=function(Y,e){g.d.call(this,{N:"div",
v2:["html5-endscreen","ytp-player-content",e||"base-endscreen"]});this.created=!1;this.player=Y},uZ=function(Y){g.d.call(this,{N:"div",
v2:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},G:[{N:"div",j:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{N:"span",j:"ytp-upnext-top",G:[{N:"span",j:"ytp-upnext-header",Qq:"Up Next"},{N:"span",j:"ytp-upnext-title",Qq:"{{title}}"},{N:"span",j:"ytp-upnext-author",Qq:"{{author}}"}]},{N:"a",j:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Play next video"},G:[{N:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
G:[{N:"circle",j:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{N:"circle",j:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{N:"path",j:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{N:"span",j:"ytp-upnext-bottom",G:[{N:"span",j:"ytp-upnext-cancel"},{N:"span",j:"ytp-upnext-paused",
Qq:"Auto-play is paused"}]}]});this.api=Y;this.cancelButton=null;this.U=this.w7("ytp-svg-autoplay-ring");this.X=this.notification=this.K=this.suggestion=null;this.Y=new g.S2(this.kc,5E3,this);this.L=0;var e=this.w7("ytp-upnext-cancel");this.cancelButton=new g.d({N:"button",v2:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Cancel auto-play"},Qq:"Cancel"});g.S(this,this.cancelButton);this.cancelButton.listen("click",this.gZ,this);this.cancelButton.Ri(e);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.S(this,this.Y);this.api.createClientVe(this.element,this,18788);e=this.w7("ytp-upnext-autoplay-icon");this.J(e,"click",this.PB);this.api.createClientVe(e,this,115130);this.UC();this.J(Y,"autonavvisibility",this.UC);this.J(Y,"mdxnowautoplaying",this.PP4);this.J(Y,"mdxautoplaycanceled",this.E3F);g.s$(this.element,"ytp-upnext-mobile",this.api.D().L)},WMz=function(Y,e){if(e)return e;
if(Y.api.isFullscreen()){var K;Y=(K=Y.api.getVideoData())==null?void 0:K.H5;return Y===-1||Y===void 0?8E3:Y}return Y.api.LV()>=0?Y.api.LV():g.ta(Y.api.D().experiments,"autoplay_time")||1E4},HZA=function(Y,e){e=WMz(Y,e);
var K=Math,x=K.min;var z=(0,g.mJ)()-Y.L;K=x.call(K,z,e);e=e===0?1:Math.min(K/e,1);Y.U.setAttribute("stroke-dashoffset",""+-211*(e+1));e>=1&&Y.Yo()&&Y.api.getPresentingPlayerType()!==3?Y.select(!0):Y.Yo()&&Y.K.start()},bZ=function(Y){ER.call(this,Y,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.d({N:"div",j:"ytp-suggestion-panel",G:[{N:"div",v2:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Qq:"More videos"}]});this.S=new g.d({N:"div",j:"ytp-suggestions-container"});this.videos=[];this.X=null;this.U=this.T=!1;this.L=new TL(this.player);g.S(this,this.L);this.L.Ri(this.element);Y.getVideoData().jx?this.K=this.L:(this.K=new uZ(Y),g.Yw(this.player,this.K.element,4),g.S(this,this.K));this.overlay=new g.d({N:"div",
j:"ytp-autonav-overlay-cancelled-state"});g.S(this,this.overlay);this.overlay.Ri(this.element);this.Y=new g.US(this);g.S(this,this.Y);g.S(this,this.table);this.table.Ri(this.element);this.table.show();g.S(this,this.S);this.S.Ri(this.table.element);this.hide()},ku=function(Y){var e=Y.LX();
e!==Y.U&&(Y.U=e,gYz(Y.player),Y.U?(Y.L!==Y.K&&Y.L.hide(),Y.table.hide()):(Y.L!==Y.K&&Y.L.show(),Y.table.show()))},lrx=function(Y){ER.call(this,Y,"videowall-endscreen");
var e=this;this.W=Y;this.stills=[];this.X=this.videoData=null;this.Y=this.T=!1;this.S=null;g.YI(this.element,"modern-videowall-endscreen");this.L=new g.US(this);g.S(this,this.L);this.U=new g.S2(function(){g.YI(e.element,"ytp-show-tiles")},0);
g.S(this,this.U);this.table=new g.K4({N:"div",j:"ytp-modern-endscreen-content"});g.S(this,this.table);this.table.Ri(this.element);Y.getVideoData().jx?this.K=new TL(Y,!0):this.K=new uZ(Y);g.S(this,this.K);g.Yw(this.player,this.K.element,4);Y.createClientVe(this.element,this,158789);this.hide()},ol=function(Y){return g.ea(Y.player)&&Y.SG()&&!Y.X},GL=function(Y){var e=Y.LX();
e!==Y.T&&(Y.T=e,gYz(Y.player))},d4A=function(Y){ER.call(this,Y,"subscribecard-endscreen");
this.K=new g.d({N:"div",j:"ytp-subscribe-card",G:[{N:"img",j:"ytp-author-image",V:{src:"{{profilePicture}}"}},{N:"div",j:"ytp-subscribe-card-right",G:[{N:"div",j:"ytp-author-name",Qq:"{{author}}"},{N:"div",j:"html5-subscribe-button-container"}]}]});g.S(this,this.K);this.K.Ri(this.element);var e=Y.getVideoData();this.subscribeButton=new g.$4("Subscribe",null,"Unsubscribe",null,!0,!1,e.Vj,e.subscribed,"trailer-endscreen",null,Y,!1);g.S(this,this.subscribeButton);this.subscribeButton.Ri(this.K.w7("html5-subscribe-button-container"));
this.J(Y,"videodatachange",this.P2);this.P2();this.hide()},Bs=function(Y){var e=Y.D(),K=g.fP||g.t7?{style:"will-change: opacity"}:void 0,x=e.Y,z=["ytp-videowall-still"];
e.L&&z.push("ytp-videowall-show-text");g.d.call(this,{N:"a",v2:z,V:{href:"{{url}}",target:x?e.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},G:[{N:"div",j:"ytp-videowall-still-image",V:{style:"{{background}}"}},{N:"span",j:"ytp-videowall-still-info",V:{"aria-hidden":"true"},G:[{N:"span",j:"ytp-videowall-still-info-bg",G:[{N:"span",j:"ytp-videowall-still-info-content",V:K,G:[{N:"span",j:"ytp-videowall-still-info-title",Qq:"{{title}}"},
{N:"span",j:"ytp-videowall-still-info-author",Qq:"{{author_and_views}}"},{N:"span",j:"ytp-videowall-still-info-live",Qq:"Live"},{N:"span",j:"ytp-videowall-still-info-duration",Qq:"{{duration}}"}]}]}]},{N:"span",v2:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},G:[{N:"span",j:"ytp-videowall-still-listlabel-icon"},"Playlist",{N:"span",j:"ytp-videowall-still-listlabel-length",G:[" (",{N:"span",Qq:"{{playlist_length}}"},")"]}]},{N:"span",v2:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},G:[{N:"span",j:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{N:"span",j:"ytp-videowall-still-listlabel-length",Qq:" (50+)"}]}]});this.suggestion=null;this.L=x;this.api=Y;this.K=new g.US(this);g.S(this,this.K);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.K.J(Y,"videodatachange",this.onVideoDataChange);Y.createServerVe(this.element,this);this.onVideoDataChange()},LK=function(Y){ER.call(this,Y,"videowall-endscreen");
var e=this;this.W=Y;this.X=0;this.stills=[];this.Y=this.videoData=null;this.U=this.S=!1;this.C=null;this.L=new g.US(this);g.S(this,this.L);this.T=new g.S2(function(){g.YI(e.element,"ytp-show-tiles")},0);
g.S(this,this.T);var K=new g.d({N:"button",v2:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Previous"},G:[g.uW()]});g.S(this,K);K.Ri(this.element);K.listen("click",this.cB,this);this.table=new g.K4({N:"div",j:"ytp-endscreen-content"});g.S(this,this.table);this.table.Ri(this.element);K=new g.d({N:"button",v2:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Next"},G:[g.bW()]});g.S(this,K);K.Ri(this.element);K.listen("click",this.jp,this);Y.getVideoData().jx?this.K=new TL(Y,!0):this.K=
new uZ(Y);g.S(this,this.K);g.Yw(this.player,this.K.element,4);Y.createClientVe(this.element,this,158789);this.hide()},fK=function(Y){return g.ea(Y.player)&&Y.SG()&&!Y.Y},Rl=function(Y){var e=Y.LX();
e!==Y.S&&(Y.S=e,gYz(Y.player))},qc6=function(Y,e){g.d.call(this,{N:"button",
v2:["ytp-watch-on-youtube-button","ytp-button"],Qq:"{{content}}"});this.W=Y;this.buttonType=this.buttonType=e;this.Gb();this.buttonType===2&&g.YI(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Gb);this.iP(!0)},m2=function(Y){ER.call(this,Y,"watch-again-on-youtube-endscreen");
this.watchButton=new qc6(Y,1);g.S(this,this.watchButton);this.watchButton.Ri(this.element);g.pzA(Y)&&(this.K=new g.t3(Y),g.S(this,this.K),this.L=new g.d({N:"div",v2:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],V:{tabIndex:"-1"},G:[this.K]}),g.S(this,this.L),this.K.Ri(this.L.element),this.L.Ri(this.element));Y.createClientVe(this.element,this,156914);this.hide()},IrP=function(Y){g.Ms.call(this,Y);
var e=this;this.endScreen=null;this.K=this.L=this.X=!1;this.listeners=new g.US(this);g.S(this,this.listeners);var K=Y.D();Y.isEmbedsShortsMode()?this.endScreen=new m2(Y):nYn(Y)?(this.X=!0,wHn(this),this.K?this.endScreen=new bZ(Y):K.Z("delhi_modern_endscreen")?this.endScreen=new lrx(Y):this.endScreen=new LK(Y)):K.yf?this.endScreen=new d4A(Y):this.endScreen=new ER(Y);g.S(this,this.endScreen);g.Yw(Y,this.endScreen.element,4);yJZ(this);this.listeners.J(Y,"videodatachange",this.onVideoDataChange,this);
this.listeners.J(Y,g.d2("endscreen"),function(x){e.onCueRangeEnter(x)});
this.listeners.J(Y,g.qt("endscreen"),function(x){e.onCueRangeExit(x)})},wHn=function(Y){var e=Y.player.getVideoData();
if(!e||Y.K===e.M9&&Y.L===e.jx)return!1;Y.K=e.M9;Y.L=e.jx;return!0},nYn=function(Y){Y=Y.D();
return Y.jx&&!Y.yf&&!Y.disableOrganicUi},yJZ=function(Y){Y.player.l1("endscreen");
var e=Y.player.getVideoData();e=new g.HU(Math.max((e.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var K=new g.HU(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});Y.player.B_([e,K])};
g.d0.prototype.LV=g.sp(6,function(){return this.app.LV()});
g.fn.prototype.LV=g.sp(5,function(){return this.getVideoData().d3});
g.S1.prototype.vN=g.sp(4,function(Y){this.dL().vN(Y)});
g.tf.prototype.vN=g.sp(3,function(Y){this.Pm!==Y&&(this.Pm=Y,this.SY())});
g.m(OR,g.d);OR.prototype.select=function(){this.W.Gw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Rr||void 0)&&this.W.logClick(this.element)};
OR.prototype.onClick=function(Y){g.PR(Y,this.W,this.K,this.suggestion.sessionData||void 0)&&this.select()};
OR.prototype.onKeyPress=function(Y){switch(Y.keyCode){case 13:case 32:Y.defaultPrevented||(this.select(),Y.preventDefault())}};g.m(TL,g.d);g.R=TL.prototype;g.R.RN=function(Y){this.suggestion!==Y&&(this.suggestion=Y,g.kB(this.K,Y),this.playButton.updateValue("url",this.suggestion.UZ()),F7(this))};
g.R.Yo=function(){return this.X>0};
g.R.rJ=function(){this.Yo()||(this.X=Date.now(),juZ(this),AJ0(this.W,JJq(this)),g.s$(this.W.getRootNode(),"countdown-running",this.Yo()))};
g.R.h6=function(){this.ez();juZ(this);var Y=this.K.w7("ytp-autonav-endscreen-upnext-header");Y&&g.X2(Y,"Up next")};
g.R.ez=function(){this.Yo()&&(this.Y.stop(),this.X=0)};
g.R.select=function(Y){this.W.nextVideo(!1,Y===void 0?!1:Y);this.ez()};
g.R.Wz=function(Y){g.PR(Y,this.W)&&(Y.currentTarget===this.playButton.element?this.W.logClick(this.playButton.element):Y.currentTarget===this.K.w7("ytp-autonav-endscreen-link-container")&&(Y=this.K.w7("ytp-autonav-endscreen-link-container"),this.W.logVisibility(Y,!0),this.W.logClick(Y)),this.U?(this.W.O4("innertubeCommand",this.U),this.ez()):this.select())};
g.R.Ut=function(){this.W.logClick(this.cancelButton.element);g.nC(this.W,!0);this.cancelCommand&&this.W.O4("innertubeCommand",this.cancelCommand)};
g.R.onVideoDataChange=function(Y,e){rJP(this,e);Y=e.getWatchNextResponse();var K,x;Y=(K=vYU(Y))==null?void 0:(x=K.cancelButton)==null?void 0:x.buttonRenderer;this.cancelCommand=Y==null?void 0:Y.command};
g.R.u6R=function(Y){if(Sca(this)){var e=this.W.getVideoData().watchToWatchTransitionRenderer,K=e==null?void 0:e.fromColorPaletteDark;e=e==null?void 0:e.toColorPaletteDark;if(K&&e){var x=this.element;x.style.setProperty("--w2w-start-background-color",g.Vr(K.surgeColor));x.style.setProperty("--w2w-start-primary-text-color",g.Vr(K.primaryTitleColor));x.style.setProperty("--w2w-start-secondary-text-color",g.Vr(K.secondaryTitleColor));x.style.setProperty("--w2w-end-background-color",g.Vr(e.surgeColor));
x.style.setProperty("--w2w-end-primary-text-color",g.Vr(e.primaryTitleColor));x.style.setProperty("--w2w-end-secondary-text-color",g.Vr(e.secondaryTitleColor));x.style.setProperty("--w2w-animation-duration",Y+"ms")}g.s$(this.element,"ytp-w2w-animate",!0)}};
g.R.WB=function(Y){this.W.Z("web_autonav_color_transition")&&Y!==2&&g.s$(this.element,"ytp-w2w-animate",!1)};
g.R.fm=function(){var Y=this.W.LX();this.T&&this.aq!==Y&&this.iP(Y);F7(this);this.W.logVisibility(this.container.element,Y);this.W.logVisibility(this.cancelButton.element,Y);this.W.logVisibility(this.K.w7("ytp-autonav-endscreen-link-container"),Y);this.W.logVisibility(this.playButton.element,Y)};
g.R.s5=function(Y){return Y.width<400||Y.height<459};g.m(ER,g.d);g.R=ER.prototype;g.R.create=function(){this.created=!0};
g.R.destroy=function(){this.created=!1};
g.R.SG=function(){return!1};
g.R.LX=function(){return!1};
g.R.FU=function(){return!1};g.m(uZ,g.d);g.R=uZ.prototype;g.R.kc=function(){this.notification&&(this.Y.stop(),this.oo(this.X),this.X=null,this.notification.close(),this.notification=null)};
g.R.RN=function(Y){this.suggestion=Y;g.kB(this,Y,"hqdefault.jpg")};
g.R.UC=function(){this.iP(this.api.LX());this.api.logVisibility(this.element,this.api.LX());this.api.logVisibility(this.w7("ytp-upnext-autoplay-icon"),this.api.LX());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.LX())};
g.R.JR4=function(){window.focus();this.kc()};
g.R.rJ=function(Y){var e=this;this.Yo()||(g.Dg("a11y-announce","Up Next "+this.suggestion.title),this.L=(0,g.mJ)(),this.K=new g.S2(function(){HZA(e,Y)},25),HZA(this,Y),AJ0(this.api,WMz(this,Y)));
g.Kw(this.element,"ytp-upnext-autoplay-paused")};
g.R.hide=function(){g.d.prototype.hide.call(this)};
g.R.Yo=function(){return!!this.K};
g.R.h6=function(){this.ez();this.L=(0,g.mJ)();HZA(this);g.YI(this.element,"ytp-upnext-autoplay-paused")};
g.R.ez=function(){this.Yo()&&(this.K.dispose(),this.K=null)};
g.R.select=function(Y){Y=Y===void 0?!1:Y;if(this.api.D().Z("autonav_notifications")&&Y&&window.Notification&&typeof document.hasFocus==="function"){var e=Notification.permission;e==="default"?Notification.requestPermission():e!=="granted"||document.hasFocus()||(this.kc(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.A8()}),this.X=this.J(this.notification,"click",this.JR4),this.Y.start())}this.ez();this.api.nextVideo(!1,Y)};
g.R.PB=function(Y){!g.m_(this.cancelButton.element,Y.target)&&g.PR(Y,this.api)&&(this.api.LX()&&this.api.logClick(this.w7("ytp-upnext-autoplay-icon")),this.select())};
g.R.gZ=function(){this.api.LX()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.nC(this.api,!0)};
g.R.PP4=function(Y){this.api.getPresentingPlayerType();this.show();this.rJ(Y)};
g.R.E3F=function(){this.api.getPresentingPlayerType();this.ez();this.hide()};
g.R.KF=function(){this.ez();this.kc();g.d.prototype.KF.call(this)};g.m(bZ,ER);g.R=bZ.prototype;g.R.create=function(){ER.prototype.create.call(this);this.Y.J(this.player,"appresize",this.XN);this.Y.J(this.player,"onVideoAreaChange",this.XN);this.Y.J(this.player,"videodatachange",this.onVideoDataChange);this.Y.J(this.player,"autonavchange",this.lG);this.Y.J(this.player,"onAutonavCancelled",this.Et);this.onVideoDataChange()};
g.R.show=function(){ER.prototype.show.call(this);(this.T||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.nC(this.player,!1);g.ea(this.player)&&this.SG()&&!this.X?(ku(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.rJ():this.videoData.autonavState===3&&this.K.h6()):(g.nC(this.player,!0),ku(this));this.XN()};
g.R.hide=function(){ER.prototype.hide.call(this);this.K.h6();ku(this)};
g.R.XN=function(){var Y=this.player.ph(!0,this.player.isFullscreen());ku(this);F7(this.L);g.s$(this.element,"ytp-autonav-cancelled-small-mode",this.s5(Y));g.s$(this.element,"ytp-autonav-cancelled-tiny-mode",this.P7(Y));g.s$(this.element,"ytp-autonav-cancelled-mini-mode",Y.width<=400||Y.height<=360);this.overlay&&g.ln(this.overlay.element,{width:Y.width+"px"});if(!this.U)for(Y=0;Y<this.videos.length;Y++)g.s$(this.videos[Y].element,"ytp-suggestion-card-with-margin",Y%2===1)};
g.R.onVideoDataChange=function(){var Y=this.player.getVideoData();if(this.videoData!==Y&&Y){this.videoData=Y;if((Y=this.videoData.suggestions)&&Y.length||this.player.Z("web_player_autonav_empty_suggestions_fix")){var e=g.hU(this.videoData);e&&(this.K.RN(e),this.K!==this.L&&this.L.RN(e))}if(Y&&Y.length)for(e=0;e<D40.length;++e){var K=D40[e];if(Y&&Y[K]){this.videos[e]=new OR(this.player);var x=this.videos[e];K=Y[K];x.suggestion!==K&&(x.suggestion=K,g.kB(x,K));g.S(this,this.videos[e]);this.videos[e].Ri(this.S.element)}}this.XN()}};
g.R.lG=function(Y){Y===1?(this.T=!1,this.X=this.videoData.clientPlaybackNonce,this.K.ez(),this.aq&&this.XN()):(this.T=!0,this.LX()&&(Y===2?this.K.rJ():Y===3&&this.K.h6()))};
g.R.Et=function(Y){Y?this.lG(1):(this.X=null,this.T=!1)};
g.R.SG=function(){return this.videoData.autonavState!==1};
g.R.s5=function(Y){return(Y.width<910||Y.height<459)&&!this.P7(Y)&&!(Y.width<=400||Y.height<=360)};
g.R.P7=function(Y){return Y.width<800&&!(Y.width<=400||Y.height<=360)};
g.R.LX=function(){return this.aq&&g.ea(this.player)&&this.SG()&&!this.X};
var D40=[1,3,2,4];g.m(lrx,ER);g.R=lrx.prototype;g.R.create=function(){ER.prototype.create.call(this);var Y=this.player.getVideoData();Y&&(this.videoData=Y);this.Hj();this.L.J(this.player,"appresize",this.Hj);this.L.J(this.player,"onVideoAreaChange",this.Hj);this.L.J(this.player,"videodatachange",this.onVideoDataChange);this.L.J(this.player,"autonavchange",this.OB);this.L.J(this.player,"onAutonavCancelled",this.BB);Y=this.videoData.autonavState;Y!==this.S&&this.OB(Y);this.L.J(this.element,"transitionend",this.ZT)};
g.R.destroy=function(){g.Um(this.L);g.sc(this.stills);this.stills=[];ER.prototype.destroy.call(this);g.Kw(this.element,"ytp-show-tiles");this.U.stop();this.S=this.videoData.autonavState};
g.R.SG=function(){return this.videoData.autonavState!==1};
g.R.show=function(){var Y=this.aq;ER.prototype.show.call(this);g.Kw(this.element,"ytp-show-tiles");this.player.D().L?g.d6(this.U):this.U.start();(this.Y||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.nC(this.player,!1);ol(this)?(GL(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.rJ():this.videoData.autonavState===3&&this.K.h6()):(g.nC(this.player,!0),GL(this));Y!==this.aq&&this.player.logVisibility(this.element,!0)};
g.R.hide=function(){var Y=this.aq;ER.prototype.hide.call(this);this.K.h6();GL(this);Y!==this.aq&&this.player.logVisibility(this.element,!1)};
g.R.ZT=function(Y){Y.target===this.element&&this.Hj()};
g.R.Hj=function(){var Y,e,K,x;var z=((Y=this.videoData)==null?0:(e=Y.suggestions)==null?0:e.length)?(K=this.videoData)==null?void 0:K.suggestions:[(x=this.videoData)==null?void 0:g.hU(x)];if(z.length){e=this.W.ph(!0,this.W.isFullscreen());Y=Math.floor((e.width-64+16)/(g.JQ(e.width*.27,250,450)+16));e=Math.min(3,Math.floor((e.height-64)/((e.width-64-(Y-1)*16)/Y*.5625+70)));g.xI(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.YI(this.element,"ytp-modern-endscreen-limit-rows-"+e);g.s$(this.element,"ytp-modern-endscreen-single-item",Y===1);g.s$(this.element,"ytp-modern-endscreen-row-0",e===0);Y=this.table.element;Y.ariaLive="polite";this.K.RN(g.hU(this.videoData));this.K instanceof TL&&F7(this.K);g.s$(this.element,"ytp-endscreen-takeover",ol(this));GL(this);e=0;Y.ariaBusy="true";K=z.length;for(x=0;x<K;x++){var O=x%K,T=this.stills[x];T||(T=new g.oT(this.player),this.stills[x]=T,Y.appendChild(T.element));g.c5f(T,z[O]);e++}this.stills.length=
e}};
g.R.onVideoDataChange=function(){var Y=this.player.getVideoData(1);this.videoData!==Y&&(Y!=null&&g.hU(Y)?(this.videoData=Y,this.Hj()):this.player.Ii("missg",{vid:(Y==null?void 0:Y.videoId)||"",cpn:(Y==null?void 0:Y.clientPlaybackNonce)||""}))};
g.R.FU=function(){return this.K.Yo()};
g.R.OB=function(Y){Y===1?(this.Y=!1,this.X=this.videoData.clientPlaybackNonce,this.K.ez(),this.aq&&this.Hj()):(this.Y=!0,this.aq&&ol(this)&&(Y===2?this.K.rJ():Y===3&&this.K.h6()))};
g.R.BB=function(Y){if(Y){for(Y=0;Y<this.stills.length;Y++)this.W.logVisibility(this.stills[Y].element,!0);this.OB(1)}else this.X=null,this.Y=!1;this.Hj()};
g.R.LX=function(){return this.aq&&ol(this)};g.m(d4A,ER);d4A.prototype.P2=function(){var Y=this.player.getVideoData();this.K.update({profilePicture:Y.profilePicture,author:Y.author});this.subscribeButton.channelId=Y.Vj;var e=this.subscribeButton;Y.subscribed?e.K():e.L()};g.m(Bs,g.d);Bs.prototype.select=function(){this.api.Gw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Rr||void 0)&&this.api.logClick(this.element)};
Bs.prototype.onClick=function(Y){if(g.eC(this.api.D())&&this.api.Z("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var e=this.suggestion.UZ(),K={};g.IO(this.api,K);e=g.fO(e,K);g.MQ(e,this.api,Y)}else g.PR(Y,this.api,this.L,this.suggestion.sessionData||void 0)&&this.select()};
Bs.prototype.onKeyPress=function(Y){switch(Y.keyCode){case 13:case 32:Y.defaultPrevented||(this.select(),Y.preventDefault())}};
Bs.prototype.onVideoDataChange=function(){var Y=this.api.getVideoData(),e=this.api.D();this.L=Y.Fq?!1:e.Y};g.m(LK,ER);g.R=LK.prototype;g.R.create=function(){ER.prototype.create.call(this);var Y=this.player.getVideoData();Y&&(this.videoData=Y);this.FS();this.L.J(this.player,"appresize",this.FS);this.L.J(this.player,"onVideoAreaChange",this.FS);this.L.J(this.player,"videodatachange",this.onVideoDataChange);this.L.J(this.player,"autonavchange",this.Do);this.L.J(this.player,"onAutonavCancelled",this.TH);Y=this.videoData.autonavState;Y!==this.C&&this.Do(Y);this.L.J(this.element,"transitionend",this.Jq)};
g.R.destroy=function(){g.Um(this.L);g.sc(this.stills);this.stills=[];ER.prototype.destroy.call(this);g.Kw(this.element,"ytp-show-tiles");this.T.stop();this.C=this.videoData.autonavState};
g.R.SG=function(){return this.videoData.autonavState!==1};
g.R.show=function(){var Y=this.aq;ER.prototype.show.call(this);g.Kw(this.element,"ytp-show-tiles");this.player.D().L?g.d6(this.T):this.T.start();(this.U||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.nC(this.player,!1);fK(this)?(Rl(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.rJ():this.videoData.autonavState===3&&this.K.h6()):(g.nC(this.player,!0),Rl(this));Y!==this.aq&&this.player.logVisibility(this.element,!0)};
g.R.hide=function(){var Y=this.aq;ER.prototype.hide.call(this);this.K.h6();Rl(this);Y!==this.aq&&this.player.logVisibility(this.element,!1)};
g.R.Jq=function(Y){Y.target===this.element&&this.FS()};
g.R.FS=function(){var Y,e,K,x;var z=((Y=this.videoData)==null?0:(e=Y.suggestions)==null?0:e.length)?(K=this.videoData)==null?void 0:K.suggestions:[(x=this.videoData)==null?void 0:g.hU(x)];if(z.length){g.YI(this.element,"ytp-endscreen-paginate");var O=this.W.ph(!0,this.W.isFullscreen());if(Y=g.Av(this.W))Y=Y.o8()?48:32,O.width-=Y*2;var T=O.width/O.height;x=96/54;e=Y=2;var E=Math.max(O.width/96,2),u=Math.max(O.height/54,2);K=z.length;var b=K*4;for(b-=4;b>0&&(Y<E||e<u);){var k=Y/2,G=e/2,B=Y<=E-2&&b>=
G*4,L=e<=u-2&&b>=k*4;if((k+1)/G*x/T>T/(k/(G+1)*x)&&L)b-=k*4,e+=2;else if(B)b-=G*4,Y+=2;else if(L)b-=k*4,e+=2;else break}x=!1;b>=12&&K*4-b<=6&&(e>=4||Y>=4)&&(x=!0);b=Y*96;E=e*54;T=b/E<T?O.height/E:O.width/b;T=Math.min(T,2);b=Math.floor(Math.min(O.width,b*T));E=Math.floor(Math.min(O.height,E*T));O=this.table.element;O.ariaLive="polite";g.en(O,b,E);g.ln(O,{marginLeft:b/-2+"px",marginTop:E/-2+"px"});this.K.RN(g.hU(this.videoData));this.K instanceof TL&&F7(this.K);g.s$(this.element,"ytp-endscreen-takeover",
fK(this));Rl(this);b+=4;E+=4;T=0;O.ariaBusy="true";for(u=0;u<Y;u++)for(k=0;k<e;k++)if(G=T,L=0,x&&u>=Y-2&&k>=e-2?L=1:k%2===0&&u%2===0&&(k<2&&u<2?k===0&&u===0&&(L=2):L=2),G=g.Sq(G+this.X,K),L!==0){B=this.stills[T];B||(B=new Bs(this.player),this.stills[T]=B,O.appendChild(B.element));var f=Math.floor(E*k/e),U=Math.floor(b*u/Y),h=Math.floor(E*(k+L)/e)-f-4,Z=Math.floor(b*(u+L)/Y)-U-4;g.Ib(B.element,U,f);g.en(B.element,Z,h);g.ln(B.element,"transitionDelay",(k+u)/20+"s");g.s$(B.element,"ytp-videowall-still-mini",
L===1);g.s$(B.element,"ytp-videowall-still-large",L>2);L=Math.max(Z,h);g.s$(B.element,"ytp-videowall-still-round-large",L>=256);g.s$(B.element,"ytp-videowall-still-round-medium",L>96&&L<256);g.s$(B.element,"ytp-videowall-still-round-small",L<=96);G=z[G];B.suggestion!==G&&(B.suggestion=G,L=B.api.D(),f=g.tA(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.kB(B,G,f),g.eC(L)&&!B.api.Z("web_player_log_click_before_generating_ve_conversion_params")&&(L=G.UZ(),f={},g.pC(B.api,"addEmbedsConversionTrackingParams",
[f]),L=g.fO(L,f),B.updateValue("url",L)),(G=(G=G.sessionData)&&G.itct)&&B.api.setTrackingParams(B.element,G));T++}O.ariaBusy="false";g.s$(this.element,"ytp-endscreen-paginate",T<K);for(z=this.stills.length-1;z>=T;z--)Y=this.stills[z],g.Rb(Y.element),g.xY(Y);this.stills.length=T}};
g.R.onVideoDataChange=function(){var Y=this.player.getVideoData(1);this.videoData!==Y&&(Y!=null&&g.hU(Y)?(this.X=0,this.videoData=Y,this.FS()):this.player.Ii("missg",{vid:(Y==null?void 0:Y.videoId)||"",cpn:(Y==null?void 0:Y.clientPlaybackNonce)||""}))};
g.R.jp=function(){this.X+=this.stills.length;this.FS()};
g.R.cB=function(){this.X-=this.stills.length;this.FS()};
g.R.FU=function(){return this.K.Yo()};
g.R.Do=function(Y){Y===1?(this.U=!1,this.Y=this.videoData.clientPlaybackNonce,this.K.ez(),this.aq&&this.FS()):(this.U=!0,this.aq&&fK(this)&&(Y===2?this.K.rJ():Y===3&&this.K.h6()))};
g.R.TH=function(Y){if(Y){for(Y=0;Y<this.stills.length;Y++)this.W.logVisibility(this.stills[Y].element,!0);this.Do(1)}else this.Y=null,this.U=!1;this.FS()};
g.R.LX=function(){return this.aq&&fK(this)};g.m(qc6,g.d);g.R=qc6.prototype;g.R.Gb=function(){switch(this.buttonType){case 1:var Y="Watch again on YouTube";var e=156915;break;case 2:Y="Continue watching on YouTube";e=156942;break;default:Y="Continue watching on YouTube",e=156942}this.update({content:Y});this.W.hasVe(this.element)&&this.W.destroyVe(this.element);this.W.createClientVe(this.element,this,e)};
g.R.onClick=function(Y){this.W.Z("web_player_log_click_before_generating_ve_conversion_params")&&this.W.logClick(this.element);g.MQ(this.getVideoUrl(),this.W,Y);this.W.Z("web_player_log_click_before_generating_ve_conversion_params")||this.W.logClick(this.element)};
g.R.getVideoUrl=function(){var Y=!0;switch(this.buttonType){case 1:Y=!0;break;case 2:Y=!1}Y=this.W.getVideoUrl(Y,!1,!1,!0);var e=this.W.D();if(g.eC(e)){var K={};g.eC(e)&&g.pC(this.W,"addEmbedsConversionTrackingParams",[K]);Y=g.fO(Y,K)}return Y};
g.R.logVisibility=function(){this.W.logVisibility(this.element,this.aq&&this.B)};
g.R.show=function(){g.d.prototype.show.call(this);this.logVisibility()};
g.R.hide=function(){g.d.prototype.hide.call(this);this.logVisibility()};
g.R.cY=function(Y){g.d.prototype.cY.call(this,Y);this.logVisibility()};g.m(m2,ER);m2.prototype.hasSuggestions=function(){var Y;return(Y=this.K)==null?void 0:Y.hasSuggestions()};
m2.prototype.show=function(){if(this.player.getPlayerState()!==3){ER.prototype.show.call(this);var Y=this.L;if(Y){var e=this.K.hasSuggestions();g.s$(this.element,"ytp-shorts-branded-ui",e);e?Y.show():Y.hide()}var K;(K=g.Av(this.player))==null||K.vN(!0);this.player.logVisibility(this.element,!0);this.watchButton.cY(!0)}};
m2.prototype.hide=function(){ER.prototype.hide.call(this);var Y;(Y=g.Av(this.player))==null||Y.vN(!1);this.player.logVisibility(this.element,!1);this.watchButton.cY(!1)};g.m(IrP,g.Ms);g.R=IrP.prototype;g.R.JT=function(){var Y=this.player.getVideoData(),e=Y.mutedAutoplay&&(Y.limitedPlaybackDurationInSeconds>0||Y.endSeconds>0||Y.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!e)return!0;var K;var x=!!((Y==null?0:g.hU(Y))||(Y==null?0:(K=Y.suggestions)==null?0:K.length));x=!nYn(this.player)||x;Y=Y.S3;K=this.player.HH();return x&&!Y&&!K&&!e};
g.R.LX=function(){return this.endScreen.LX()};
g.R.tW=function(){return this.LX()?this.endScreen.FU():!1};
g.R.KF=function(){this.player.l1("endscreen");g.Ms.prototype.KF.call(this)};
g.R.load=function(){var Y=this.player.getVideoData();var e=Y.transitionEndpointAtEndOfStream;if(e&&e.videoId){var K=this.player.Rq().Me.get("heartbeat"),x=g.hU(Y);!x||e.videoId!==x.videoId||Y.V7?(this.player.Gw(e.videoId,void 0,void 0,!0,!0,e),K&&K.Di("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),Y=!0):Y=!1}else Y=!1;Y||(g.Ms.prototype.load.call(this),this.endScreen.show())};
g.R.unload=function(){g.Ms.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.R.onCueRangeEnter=function(Y){this.JT()&&(this.endScreen.created||this.endScreen.create(),Y.getId()==="load"&&this.load())};
g.R.onCueRangeExit=function(Y){Y.getId()==="load"&&this.loaded&&this.unload()};
g.R.onVideoDataChange=function(){yJZ(this);this.X&&wHn(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.K?this.endScreen=new bZ(this.player):this.endScreen=new LK(this.player),g.S(this,this.endScreen),g.Yw(this.player,this.endScreen.element,4))};g.PA("endscreen",IrP);})(_yt_player);
