(function(g){var window=this;'use strict';var t_A=function(Y,e){if(!Number.isFinite(Y))return String(Y);Y=String(Y);var K=Y.indexOf(".");K===-1&&(K=Y.length);var x=Y[0]==="-"?"-":"";x&&(Y=Y.substring(1));return x+(0,g.nxL)("0",Math.max(0,e-K))+Y},Yrd=function(){return{N:"svg",
V:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},G:[{N:"path",V:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},eXz=function(){return{N:"svg",
V:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},G:[{N:"path",V:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},xZU=function(Y){typeof Y==="number"?(this.date=Kk0(Y,0,1),X7(this,1)):g.$x(Y)?(this.date=Kk0(Y.getFullYear(),Y.getMonth(),Y.getDate()),X7(this,Y.getDate())):(this.date=new Date(g.kx()),Y=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),X7(this,Y))},Kk0=function(Y,e,K){e=new Date(Y,e,K);
Y>=0&&Y<100&&e.setFullYear(e.getFullYear()-1900);return e},X7=function(Y,e){Y.getDate()!=e&&Y.date.setUTCHours(Y.date.getUTCHours()+(Y.getDate()<e?1:-1))},al=function(Y,e){g.O7.call(this,Y,{N:"div",
j:"ytp-reminder-menu",V:{role:"menu",tabindex:"-1"},G:[{N:"div",j:"ytp-reminder-menu-contents",G:[{N:"div",j:"ytp-reminder-menu-items"}]}]},100,!0);this.K=e;this.X=[];this.menuPopupRenderer=void 0;this.items=this.w7("ytp-reminder-menu-items");this.hide()},soP=function(Y){return(Y.menuPopupRenderer&&Y.menuPopupRenderer.items||[]).reduce(function(e,K){K&&K.menuServiceItemRenderer&&e.push(K.menuServiceItemRenderer);
return e},[])},UR=function(Y){g.d.call(this,{N:"div",
G:[{N:"button",v2:["ytp-offline-slate-button","ytp-button"],G:[{N:"div",j:"ytp-offline-slate-button-icon",Qq:"{{icon}}"},{N:"div",j:"ytp-offline-slate-button-text",Qq:"{{text}}"}]}]});this.W=Y;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.L=void 0;this.Y=this.K=null;(this.U=this.w7("ytp-offline-slate-button"))&&this.J(this.U,"click",this.T);this.hide()},$Z7=function(Y,e,K){!Y.toggleButtonRenderer&&e&&e.toggleButtonRenderer?Y.toggleButtonRenderer=e.toggleButtonRenderer:
e&&e.toggleButtonRenderer||(Y.toggleButtonRenderer=null);
!Y.upcomingEventReminderButtonRenderer&&K&&g.l(K,zXA)?Y.upcomingEventReminderButtonRenderer=g.l(K,zXA):K&&g.l(K,zXA)||(Y.upcomingEventReminderButtonRenderer=null);Q2(Y)},Q2=function(Y){if(Y.toggleButtonRenderer){var e=Y.toggleButtonRenderer;
if(e.isToggled){var K=e.toggledText?g.TC(e.toggledText):"";Y.update({text:K,icon:OB7(e.toggledIcon)})}else K=e.defaultText?g.TC(e.defaultText):"",Y.update({text:K,icon:OB7(e.defaultIcon)});Y.show()}else Y.upcomingEventReminderButtonRenderer?(e=TTd(Y))?(K=e.text?g.TC(e.text):"",Y.update({text:K,icon:OB7(e.icon)}),Y.show()):Y.hide():Y.hide()},E3a=function(Y,e,K){Y.Y||(Y.Y=new g.HV(Y.W.D().Va));
var x={context:g.$E(Y.Y.config_||g.sB())};g.Ld()&&(x.context.clientScreenNonce=g.Ld());x.params=K;g.lt(Y.Y,e,x,{timeout:5E3,onSuccess:function(){Y.upcomingEventReminderButtonRenderer&&Y.L&&(Y.upcomingEventReminderButtonRenderer.currentState=Y.L,Y.L=void 0)},
onError:function(){FkU(Y)},
onTimeout:function(){FkU(Y)}})},FkU=function(Y){Y.toggleButtonRenderer?(Y.toggleButtonRenderer.isToggled=!Y.toggleButtonRenderer.isToggled,Q2(Y)):Y.upcomingEventReminderButtonRenderer&&(Y.L=void 0,Q2(Y))},OB7=function(Y){if(!Y)return null;
switch(Y.iconType){case "NOTIFICATIONS":return Yrd();case "NOTIFICATIONS_NONE":return eXz();case "NOTIFICATIONS_ACTIVE":return g.L4();default:return null}},TTd=function(Y){if(!Y.upcomingEventReminderButtonRenderer)return null;
var e=Y.L||Y.upcomingEventReminderButtonRenderer.currentState;Y=g.a(Y.upcomingEventReminderButtonRenderer.states||[]);for(var K=Y.next();!K.done;K=Y.next())if((K=g.l(K.value,u1d))&&K.state===e&&K.button&&g.l(K.button,g.Ea))return g.l(K.button,g.Ea);return null},bBM=function(Y){g.d.call(this,{N:"div",
j:"ytp-offline-slate",G:[{N:"div",j:"ytp-offline-slate-background"},{N:"div",j:"ytp-offline-slate-bar",G:[{N:"span",j:"ytp-offline-slate-icon",G:[{N:"svg",V:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},G:[{N:"path",V:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{N:"circle",V:{cx:"12",cy:"12",r:"3"}}]}]},{N:"span",j:"ytp-offline-slate-messages",G:[{N:"div",j:"ytp-offline-slate-main-text",V:{"aria-label":"{{label}}"},Qq:"{{mainText}}"},{N:"div",j:"ytp-offline-slate-subtitle-text",Qq:"{{subtitleText}}"}]},{N:"span",j:"ytp-offline-slate-buttons"}]},{N:"button",v2:["ytp-offline-slate-close-button","ytp-button"],G:[g.bW()]},{N:"button",v2:["ytp-offline-slate-open-button","ytp-button"],G:[g.uW()]}]});var e=this;this.api=Y;this.K=this.L=null;this.background=this.w7("ytp-offline-slate-background");
this.X=this.w7("ytp-offline-slate-bar");this.U=new g.S2(function(){g.YI(e.X,"ytp-offline-slate-bar-fade")},15E3);
this.T=!1;this.Y=new g.S2(function(){g.YI(e.element,"ytp-offline-slate-collapsed")},15E3);
g.S(this,this.Y);g.S(this,this.U);this.countdownTimer=new g.S2(this.n$,1E3,this);this.J(Y,"presentingplayerstatechange",this.Qp);this.J(Y,"livestatedata",this.P2);this.J(this.w7("ytp-offline-slate-close-button"),"click",function(){g.YI(e.element,"ytp-offline-slate-collapsed")});
this.J(this.w7("ytp-offline-slate-open-button"),"click",function(){g.Kw(e.element,"ytp-offline-slate-collapsed")});
this.hide();Y=this.getVideoData();Y.getPlayerResponse()&&(Y=Y.getPlayerResponse().playabilityStatus)&&this.P2(Y);Y=this.api.getPresentingPlayerType()===8&&!this.getVideoData().x6;var K=this.api.getPresentingPlayerType()===8;g.s$(this.element,"ytp-offline-slate-premiere-trailer",Y);g.s$(this.element,"ytp-offline-slate-hide-background",K)},kTP=function(Y,e,K){if(e){var x=e.subtitleText!=null?g.TC(e.subtitleText):"";
K=K?K:e.mainText!=null?g.TC(e.mainText):"";var z,O,T,E;e=(E=(z=e.mainText)==null?void 0:(O=z.accessibility)==null?void 0:(T=O.accessibilityData)==null?void 0:T.label)!=null?E:K;Y.update({mainText:K,subtitleText:x,label:e});g.s$(Y.element,"ytp-offline-slate-single-text-line",!x);g.s$(Y.X,"ytp-offline-slate-bar-hidden",!K&&!x)}},h9=function(Y,e){var K=(0,g.mJ)();
this.trigger=Y;this.K=e;this.X=K},RXd=function(Y){g.Ms.call(this,Y);
var e=this;this.T=!1;this.S=0;this.B=!1;this.L=new g.S2(function(){o3P(e)},0);
this.K=this.heartbeatParams=null;this.Y=!1;this.U=new g.V3(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.nF=new g.HV(void 0);this.attestationResponse=Promise.resolve(void 0);this.C=Promise.resolve(void 0);this.utcOffsetMinutes=-(new xZU).getTimezoneOffset();this.X=new g.US(this);g.S(this,this.L);g.S(this,this.X);GTZ(this);BTa(this);this.X.J(Y,"heartbeatparams",this.kA);this.X.J(Y,"presentingplayerstatechange",this.rZ);this.X.J(Y,"videoplayerreset",this.Sp);this.X.J(Y,g.d2("heartbeat"),
this.onCueRangeEnter);this.Y&&this.K&&Lkn(this,void 0,this.K);var K=new g.HU(Ps(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),x=new g.HU(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});Y.B_([K,x]);fV7(this)},fV7=function(Y){var e=Y.getVideoData();
!e.Z("use_rta_for_player")&&e.Cz&&(e=e.botguardData)&&g.ow(e,Y.player.D())},mZP=function(Y){var e,K;
return g.C(function(x){if(x.L==1)return g.c(x,g.Ct$(),2);if(!x.K)return Y.sequenceNumber>=3?x.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):x.return(void 0);e=Y.getVideoData();K={};return x.return(g.VZ8((K.cpn=e.clientPlaybackNonce,K.encryptedVideoId=e.videoId||"",K),1500))})},GTZ=function(Y){var e=Y.getVideoData();
if(e.Cz)if(e.Z("use_rta_for_player"))Y.attestationResponse=mZP(Y);else if(e=new g.ldM(e),g.ur.isInitialized()||Y.sequenceNumber>=3){var K=Promise,x=K.resolve,z=null;if(e.videoData.xN){var O=g.dt8(e);if(O){z={};var T={};O=O.split("&");O=g.a(O);for(var E=O.next();!E.done;E=O.next())E=E.value.split("="),E.length===2&&(T[E[0]]=E[1]);T.r1a&&(z.webResponse=T.r1a);T.r1c&&(z.error=XM0[Number(T.r1c)]);z.challenge=e.videoData.xN}}Y.attestationResponse=x.call(K,z||void 0)}},aV7=function(Y){var e=Y.getVideoData();
if(!g.d7(Y.getVideoData())||e.wF)return!1;if(e.B){Y=e.B.flavor==="playready"&&e.Z("html5_innertube_heartbeats_for_playready");var K=e.B.flavor==="widevine"&&e.Z("html5_innertube_heartbeats_for_widevine");e=g.bG(e.B)&&e.Z("html5_innertube_heartbeats_for_fairplay");return!(Y||K||e)}return!0},UZn=function(Y){if(aV7(Y))return!!Y.heartbeatParams;
var e=Y.getVideoData();return!g.d7(Y.getVideoData())||e.xC||e.MN?!!e.heartbeatToken:!1},MA=function(Y,e){if(!Y.L.isActive()&&Y.T){var K=Y.getVideoData();
if(UZn(Y)||K.isLivePlayback){if(e===void 0)if(Y.B)if(Y.Y)e=7500;else{var x;e=((x=Y.heartbeatParams)==null?0:x.interval)?Y.heartbeatParams.interval*1E3:Y.getVideoData().UN||6E4}else e=1E3;Y.L.start(e)}}},MB1=function(Y,e,K){e.ev&&(K=g.fO(K,{internalipoverride:e.ev}));
var x={cpn:e.clientPlaybackNonce};e.contextParams&&(x.context_params=e.contextParams);e.vn&&(x.kpt=e.vn);K=g.fO(K,x);g.RE(K,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(z){if(!Y.L.isActive()&&NA(Y)){Y.U.reset();Y.sequenceNumber++;z=z.responseText;var O=Qo7(z);if(O){Y.player.O4("onHeartbeat",O);var T=O.status==="ok"?O.stop_heartbeat?2:0:O.status==="stop"?1:O.status==="live_stream_offline"?0:-1}else T=(T=z.match(hX1))?T[1]==="0"?0:1:-1;Pyn(Y,void 0,O,z,T)}},
onError:function(z){NA(Y)&&ZP(Y,!0,"net-"+z.status)},
onTimeout:function(){NA(Y)&&ZP(Y,!0,"timeout")},
withCredentials:!0})},o3P=function(Y){var e,K;
g.C(function(x){e=Y.player.D();K=Y.getVideoData();if(!NA(Y))return x.return();if(aV7(Y))return NTa(Y,e,K),x.mR(0);GTZ(Y);return g.c(x,ZBU(Y,e,K),0)})},NTa=function(Y,e,K){var x;
if((x=Y.heartbeatParams)!=null&&x.url){var z=g.fO(Y.heartbeatParams.url,{request_id:g.UgO()});K.X6&&(z=g.fO(z,{vvt:K.X6}),K.mdxEnvironment&&(z=g.fO(z,{mdx_environment:K.mdxEnvironment})));g.VB(e,K.oauthToken).then(function(O){O&&(z=g.fO(z,{access_token:O}));MB1(Y,K,z)})}},NA=function(Y){var e=Y.getVideoData();
return Y.player.getPresentingPlayerType()===3||g.n(Y.player.getPlayerStateObject(Y.getPlayerType()),4)?!1:UZn(Y)||e.isLivePlayback?!0:(pK(Y),!1)},ZBU=function(Y,e,K){var x,z,O,T,E,u,b,k,G,B,L,f,U,h,Z,N,V,r,H,I;
return g.C(function(w){if(w.L==1)return x="player/heartbeat",O={videoId:K.videoId,sequenceNumber:Y.sequenceNumber,heartbeatServerData:(z=Y.xq)!=null?z:K.heartbeatServerData},Y.C=Y.attestationResponse,K.Cz?g.c(w,Y.C,3):w.mR(2);w.L!=2&&(O.attestationResponse=w.K);T=g.hv(K);u=(E=T.client)!=null?E:{};u.utcOffsetMinutes=Y.utcOffsetMinutes;O.context=T;O.cpn=K.clientPlaybackNonce;if(b=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)u.timeZone=b;k={heartbeatChecks:[]};
if(G=K.getPlayerResponse())K.heartbeatToken&&(O.heartbeatToken=K.heartbeatToken),(B=G.playabilityStatus)&&(L=B.liveStreamability)&&L.liveStreamabilityRenderer&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");K.heartbeatToken&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.bS(e)&&(k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),f=pMM(Y),U={},f!==null&&(U.clientPlayerPositionUtcMillis=f),Z=(h=Y.player.Rq())==null?void 0:g.r3(h),V=((N=Z)==null?void 0:N.freePreviewWatchedDuration)||
0,V>0&&(U.freePreviewWatchedDuration={seconds:""+V}),k.unpluggedParams=U);O.heartbeatRequestParams=k;K.isLivePlayback?(r=pMM(Y),r!==null&&(O.playbackState||(O.playbackState={}),O.playbackState.playbackPosition={utcTimeMillis:r})):e.Z("enable_heartbeat_vod_playback_position")&&(H=cwz(Y),H!==null&&(O.playbackState||(O.playbackState={}),O.playbackState.playbackPosition={streamTimeMillis:H}));Y.player.publish("heartbeatRequest",O);I={timeout:3E4,onSuccess:function($O){if(!Y.L.isActive()&&NA(Y)){var GM=
Y.getVideoData(),TM=GM.Cz&&Y.C==null,F9;GM.Cz=!((F9=$O.heartbeatAttestationConfig)==null||!F9.requiresAttestation)||TM;TM=$O.playabilityStatus;F9=JSON.stringify(TM)||"{}";$O.authenticationMismatch&&Y.player.Ii("authshear",{});var ec=-1;var NP=$O.playabilityStatus;NP&&(Y.player.O4("onHeartbeat",NP),NP.status==="OK"?ec=$O.stopHeartbeat?2:0:NP.status==="UNPLAYABLE"?ec=1:NP.status==="LIVE_STREAM_OFFLINE"&&(ec=0));Y.sequenceNumber&&ec===-1||Y.U.reset();Y.sequenceNumber++;$O.heartbeatServerData&&(Y.xq=
$O.heartbeatServerData);GM.FN=$O;(NP=$O.playerCueRangeSet)&&g.aR(GM,NP);$O.playerCueRanges&&$O.playerCueRanges.length>0&&(GM.cueRanges=$O.playerCueRanges);var y$,e6;((y$=$O.progressBarConfig)==null?0:y$.progressBarStartPosition)&&((e6=$O.progressBarConfig)==null?0:e6.progressBarEndPosition)&&(GM.progressBarStartPosition=$O.progressBarConfig.progressBarStartPosition,GM.progressBarEndPosition=$O.progressBarConfig.progressBarEndPosition);GM.compositeLiveIngestionOffsetToken=$O.compositeLiveIngestionOffsetToken;
$O.compositeLiveStatusToken!==GM.compositeLiveStatusToken&&(GM.compositeLiveStatusToken=$O.compositeLiveStatusToken);GM.publish("dataupdated");Pyn(Y,$O,TM,F9,ec)}},
onError:function($O){NA(Y)&&ZP(Y,!0,"net-"+$O.status)},
onTimeout:function(){NA(Y)&&ZP(Y,!0,"timeout")}};
g.VB(e,g.uJ(K)).then(function($O){$O&&(I.jh="Bearer "+$O);g.lt(Y.nF,x,O,I)});
g.aS(w)})},Pyn=function(Y,e,K,x,z){z===-1?(K="decode "+g.NJ(x,3),ZP(Y,!1,K)):z===2?(pK(Y),Y.B=!0):(Y.S=0,Y.L.stop(),z===1?(Y.B=!1,K&&K.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&Y.player.B$(!0),z="pe."+(K==null?void 0:K.errorCode)+";ps."+(K==null?void 0:K.status),Y.player.Qf("heartbeat.stop",2,Y.aG(x),z),g.KV("heartbeatActionPlayerHalted",VBU(K)),(e==null?0:e.videoTransitionEndpoint)&&K&&(e=e.videoTransitionEndpoint,(x=g.l(e,g.QW))&&Cyz(Y,x,K,{itct:e==null?void 0:e.clickTrackingParams}))):(Y.B=
!0,x=0,Y.Y&&K&&(x=Lkn(Y,e,K),Y.player.publish("livestatedata",K)),x?MA(Y,x):MA(Y)))},Lkn=function(Y,e,K){var x=K.liveStreamability&&K.liveStreamability.liveStreamabilityRenderer,z=!(!x||!(x.switchStreamsImmediately||x.transitionTiming&&x.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
e=g36(Y,e,x);var O=Y.getVideoData(),T=Y.player.getPlayerStateObject(Y.getPlayerType()),E=T.isPlaying()&&!g.tU(O)&&!Y.player.isAtLiveHead(Y.getPlayerType());if(O.D().tR()){var u,b=((u=Y.player.uq())==null?void 0:u.zX())||{};b.status=K.status||"";b.dvr=""+ +E;b["switch"]=""+ +z;b.ended=""+ +!(!x||!x.displayEndscreen);Y.player.Ii("heartbeat",b)}u=Y.player.Z("always_cache_redirect_endpoint");if(E&&!z&&!u)return e;b=x&&x.streamTransitionEndpoint&&g.l(x.streamTransitionEndpoint,g.QW);var k=x&&x.transitionTiming;
if(k==="STREAM_TRANSITION_TIMING_AT_STREAM_END")Y.getVideoData().transitionEndpointAtEndOfStream=b;else if(u&&!b&&Y.getVideoData().transitionEndpointAtEndOfStream)Y.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!u&&b&&Cyz(Y,b,K))return e;if(E&&!z&&u||u&&b&&(k==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||k==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&Cyz(Y,b,K))return e;if(K.status.toUpperCase()==="OK"){z=x&&x.broadcastId;E=Y.K&&Y.K.liveStreamability&&Y.K.liveStreamability.liveStreamabilityRenderer&&
Y.K.liveStreamability.liveStreamabilityRenderer.broadcastId;u=z!==E&&z!=null;if(!g.yW(O)||u){var G={video_id:O.videoId};O.I1&&(G.is_live_destination="1");G.disable_watch_next=!0;G.raw_watch_next_response=O.getWatchNextResponse();G.autonav_state=O.autonavState;G.oauth_token=O.oauthToken;G.qY=O.qY;O.U&&(G.vss_credentials_token=O.U,G.vss_credentials_token_type=O.zw);O.X6&&(G.vvt=O.X6);x=void 0;g.yW(O)?u&&(x=new h9("broadcastIdChanged",E+","+z),Y.Di("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",
K)):(z&&(x=new h9("formatsReceived",""+z)),Y.Di("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",K));Y.player.loadVideoByPlayerVars(G,void 0,void 0,void 0,x);return e}Y.player.mD("heartbeat",Y.getPlayerType())}x&&x.displayEndscreen&&(Y.offlineSlate?(Y=Y.offlineSlate,Y.T=!0,Y.aq&&Y.api.a5()):T.isBuffering()&&(O=((G=Y.player.uq())==null?void 0:G.zX())||{},Y.player.Ii("hbse",O,!0),Y.player.Z("html5_report_eos")?Y.player.a5(!0,"h"):Y.player.a5(),Y.player.O4("onLiveMediaEnded",
K)));return e},g36=function(Y,e,K){return Y.player.Z("web_player_use_heartbeat_poll_delay_ms")&&(Y=Number(e==null?void 0:e.pollDelayMs))?Y:(K=Number(K==null?void 0:K.pollDelayMs))?K:0},ZP=function(Y,e,K){if(!Y.L.isActive()){Y.L.stop();
Y.S++;var x=e?"heartbeat.net":"heartbeat.servererror";var z=Y.getVideoData();if(z.pn||e&&!g.d7(Y.getVideoData())&&!UZn(Y)&&z.isLivePlayback)z=!1;else{var O,T;((T=Y.heartbeatParams)==null?0:T.retries)?O=Y.heartbeatParams.retries:O=z.mu||5;z=Y.S>=O}z?(g.KV("heartbeatActionPlayerHalted",e?{enforcedPolicyToHaltOnNetworkFailure:!0}:VBU()),(e=Y.getVideoData())&&e.isLivePlayback?Y.player.Qf(x,1,"Video playback interrupted. Please try again.",K):Y.player.Qf(x,1,"Sorry, there was an error while licensing this video.",
K)):(MA(Y,Y.U.getValue()),g.CM(Y.U))}},VBU=function(Y){var e={enforcedPolicyToHaltOnNetworkFailure:!1};
Y&&(e.serializedServerContext=Y.additionalLoggingData);return e},pK=function(Y){Y.S=0;
Y.L.stop();Y.B=!1;Y.sequenceNumber=0},BTa=function(Y){var e=Y.getVideoData(),K=Y.player.D();
if(e.isLivePlayback)if(g.QO(K.B)){Y.Y=!0;Y.T=!0;if(!g.o3(K)||g.bS(K))Y.offlineSlate=new bBM(Y.player),g.S(Y,Y.offlineSlate),g.Yw(Y.player,Y.offlineSlate.element,4);(e=e.getPlayerResponse())&&e.playabilityStatus&&(Y.K=e.playabilityStatus);var x;((x=Y.K)==null?void 0:x.status)!=="UNPLAYABLE"&&(Y.K?(x=g36(Y,void 0,Y.K.liveStreamability&&Y.K.liveStreamability.liveStreamabilityRenderer))?MA(Y,x):MA(Y,7500):MA(Y,Ps(Y,!0)))}else Y.player.Qf("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK",
"nolive.1");else g.an(e.C,"heartbeat")&&Y.player.mD("heartbeat",Y.getPlayerType())},Cyz=function(Y,e,K,x){var z=e&&e.videoId;
return z?(Y.player.Gw(z,Object.assign({},{autonav:"1"},x||{}),void 0,!0,!0,e,g.uJ(Y.getVideoData())),Y.Di("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",K),!0):!1},pMM=function(Y){return(Y=Y.player.getProgressState(Y.getPlayerType()).ingestionTime)&&isFinite(Y)?""+Math.floor(Y*1E3):null},cwz=function(Y){return(Y=Y.player.getCurrentTime(Y.getPlayerType()))&&isFinite(Y)?""+Math.floor(Y*1E3):null},Ps=function(Y,e){e=e===void 0?!1:e;
Y=Y.getVideoData();return Y.Z("html5_use_server_init_heartbeat_delay")?isNaN(Y.UN)?15E3:Y.UN:e?1E3:2E3},Qo7=function(Y){try{var e=JSON.parse(Y);
return e!=null?e:void 0}catch(K){}},Aw6={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
Aw6={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["am","pm"],DATEFORMATS:["EEEE, d MMMM y",
"d MMMM y","d MMM y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:3};
var XM0=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],v30={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.R=xZU.prototype;g.R.aZ=Aw6.FIRSTDAYOFWEEK;g.R.eZ=Aw6.FIRSTWEEKCUTOFFDAY;
g.R.clone=function(){var Y=new xZU(this.date);Y.aZ=this.aZ;Y.eZ=this.eZ;return Y};
g.R.getFullYear=function(){return this.date.getFullYear()};
g.R.getYear=function(){return this.getFullYear()};
g.R.getMonth=function(){return this.date.getMonth()};
g.R.getDate=function(){return this.date.getDate()};
g.R.getTime=function(){return this.date.getTime()};
g.R.getDay=function(){return this.date.getDay()};
g.R.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.R.getUTCMonth=function(){return this.date.getUTCMonth()};
g.R.getUTCDate=function(){return this.date.getUTCDate()};
g.R.getUTCDay=function(){return this.date.getDay()};
g.R.getUTCHours=function(){return this.date.getUTCHours()};
g.R.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.R.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.R.set=function(Y){this.date=new Date(Y.getFullYear(),Y.getMonth(),Y.getDate())};
g.R.setFullYear=function(Y){this.date.setFullYear(Y)};
g.R.setYear=function(Y){this.setFullYear(Y)};
g.R.setMonth=function(Y){this.date.setMonth(Y)};
g.R.setDate=function(Y){this.date.setDate(Y)};
g.R.setTime=function(Y){this.date.setTime(Y)};
g.R.setUTCFullYear=function(Y){this.date.setUTCFullYear(Y)};
g.R.setUTCMonth=function(Y){this.date.setUTCMonth(Y)};
g.R.setUTCDate=function(Y){this.date.setUTCDate(Y)};
g.R.add=function(Y){if(Y.years||Y.months){var e=this.getMonth()+Y.months+Y.years*12,K=this.getYear()+Math.floor(e/12);e%=12;e<0&&(e+=12);a:{switch(e){case 1:var x=K%4!=0||K%100==0&&K%400!=0?28:29;break a;case 5:case 8:case 10:case 3:x=30;break a}x=31}x=Math.min(x,this.getDate());this.setDate(1);this.setFullYear(K);this.setMonth(e);this.setDate(x)}Y.days&&(K=this.getYear(),e=K>=0&&K<=99?-1900:0,Y=new Date((new Date(K,this.getMonth(),this.getDate(),12)).getTime()+Y.days*864E5),this.setDate(1),this.setFullYear(Y.getFullYear()+
e),this.setMonth(Y.getMonth()),this.setDate(Y.getDate()),X7(this,Y.getDate()))};
g.R.equals=function(Y){return!(!Y||this.getYear()!=Y.getYear()||this.getMonth()!=Y.getMonth()||this.getDate()!=Y.getDate())};
g.R.toString=function(){var Y=this.getFullYear(),e=Y<0?"-":Y>=1E4?"+":"";return[e+t_A(Math.abs(Y),e?6:4),t_A(this.getMonth()+1,2),t_A(this.getDate(),2)].join("")+""};
g.R.valueOf=function(){return this.date.valueOf()};var rwn=new g.RD("addUpcomingEventReminderEndpoint");var jo0=new g.RD("removeUpcomingEventReminderEndpoint");var iBZ=new g.RD("updateUpcomingEventReminderButtonStateCommand");var zXA=new g.RD("upcomingEventReminderButtonRenderer"),u1d=new g.RD("upcomingEventReminderButtonStateRenderer");g.m(al,g.O7);
al.prototype.updateMenuItems=function(){var Y=this,e=soP(this),K=0;K=0;for(var x={};K<e.length;x={ov:void 0},K++){var z=this.X[K];z||(z=new g.d({N:"div",j:"ytp-reminder-menu-item",V:{role:"menuitem",tabindex:"0"},G:[{N:"div",j:"ytp-reminder-menu-item-icon",Qq:"{{icon}}"},{N:"div",j:"ytp-reminder-menu-item-label",Qq:"{{text}}"}]}),x.ov=K,z.listen("click",function(T){return function(){var E=T.ov;Y.Nn();E=soP(Y)[E];Y.publish("reminderMenuItemClicked",E.serviceEndpoint||E.command)}}(x)),z.Ri(this.items),
this.X[K]=z);
var O=e[K];x=null;switch(O.icon&&O.icon.iconType){case "NOTIFICATIONS":x=Yrd();break;case "NOTIFICATIONS_NONE":x=eXz();break;case "NOTIFICATIONS_ACTIVE":x=g.L4()}O=O.text?g.TC(O.text):"";z.update({icon:x,text:O})}for(;K<this.X.length;)this.X.pop().dispose();K===0?this.Nn():this.ZO(this.K)};
al.prototype.hide=function(){this.K&&this.K.removeAttribute("aria-haspopup");g.O7.prototype.hide.call(this)};
al.prototype.show=function(){this.K&&this.K.setAttribute("aria-haspopup","true");g.O7.prototype.show.call(this)};
al.prototype.KF=function(){g.sc(this.X);g.O7.prototype.KF.call(this)};g.m(UR,g.d);
UR.prototype.T=function(){if(this.toggleButtonRenderer){var Y=this.toggleButtonRenderer;Y.isToggled?this.X(Y.toggledServiceEndpoint):this.X(Y.defaultServiceEndpoint);Y.isToggled=!Y.isToggled;Q2(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.K&&this.K.aq)this.K.Nn();else{var e=TTd(this);e&&this.X(e.serviceEndpoint||e.command);e=((Y=g.l(e==null?void 0:e.command,g.uk))==null?void 0:Y.commands)||[];a:{Y=g.a(e);for(var K=Y.next();!K.done;K=Y.next()){var x=e=void 0;if(K=(e=g.l(K.value,g.zc7))==
null?void 0:(x=e.popup)==null?void 0:x.menuPopupRenderer){Y=K;break a}}Y=void 0}this.K||(this.K=new al(this.W,this.U),this.K.Ri(this.element),g.S(this,this.K),this.K.subscribe("reminderMenuItemClicked",this.X,this));e=this.K;e.menuPopupRenderer=Y;e.updateMenuItems()}};
UR.prototype.X=function(Y){var e=g.l(Y,rwn),K=g.l(Y,jo0);if(Y&&(e||K)){if(e){var x=e;var z="notification/add_upcoming_event_reminder"}else K&&(x=K,z="notification/remove_upcoming_event_reminder");if(z&&x&&x.params)for(E3a(this,z,x.params),Y=g.a(x.commands||[]),e=Y.next();!e.done;e=Y.next())if((e=e.value)&&g.l(e,iBZ)){this.L=g.l(e,iBZ).state;Q2(this);break}}};g.m(bBM,g.d);g.R=bBM.prototype;g.R.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.R.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.R.P2=function(Y){var e,K,x=Y==null?void 0:(e=Y.liveStreamability)==null?void 0:(K=e.liveStreamabilityRenderer)==null?void 0:K.offlineSlate;if(x){this.L=Y;e=x.liveStreamOfflineSlateRenderer;e.canShowCountdown?this.n$():kTP(this,e);var z,O,T,E;if(K=Y==null?void 0:(z=Y.liveStreamability)==null?void 0:(O=z.liveStreamabilityRenderer)==null?void 0:(T=O.offlineSlate)==null?void 0:(E=T.liveStreamOfflineSlateRenderer)==null?void 0:E.thumbnail){z=0;O=null;T=K.thumbnails;for(E=0;E<T.length;E++)T[E].width>
z&&(z=T[E].width||0,O=T[E].url);O&&(this.background.style.backgroundImage="url("+O+")")}else this.background.style.backgroundImage="";e.actionButtons||e.reminderButton?(this.K||(this.K=new UR(this.api),this.K.Ri(this.w7("ytp-offline-slate-buttons")),g.S(this,this.K)),$Z7(this.K,e.actionButtons&&e.actionButtons[0],e.reminderButton)):this.K&&$Z7(this.K,null,null);this.L=Y}else this.L=null;this.Qp()};
g.R.Qp=function(Y){if(this.api.getPresentingPlayerType()===8)var e=!0;else{var K=this.api.getPlayerStateObject(),x=this.getVideoData();e=x.isLivePlayback&&(K.isBuffering()||g.n(K,2)||g.n(K,64));var z=x.autonavState===2&&g.n(K,2);K=K.isPlaying()&&!g.tU(x)&&!this.api.isAtLiveHead(void 0,!0);e=e&&!K&&!z}e&&this.L?this.aq?(Y==null?0:g.FU(Y,2))&&!this.getVideoData().x6&&(g.Kw(this.element,"ytp-offline-slate-collapsed"),this.Y.stop(),g.Kw(this.X,"ytp-offline-slate-bar-fade"),this.U.start()):(this.show(),
this.Y.start(),this.api.publish("offlineslatestatechange"),this.T&&this.api.a5()):this.aq&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.R.n$=function(){var Y,e,K,x,z=(Y=this.L)==null?void 0:(e=Y.liveStreamability)==null?void 0:(K=e.liveStreamabilityRenderer)==null?void 0:(x=K.offlineSlate)==null?void 0:x.liveStreamOfflineSlateRenderer;z&&(Y=Math.floor(g.kx()/1E3),e=z.canShowCountdown&&Number(z.scheduledStartTime),!e||e<=Y?(kTP(this,z),this.countdownTimer.stop()):(kTP(this,z,g.fX(e-Y)),g.lL(this.countdownTimer)))};
g.R.KF=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.d.prototype.KF.call(this)};h9.prototype.L=function(Y){return this.trigger&&Y.trigger?this.trigger===Y.trigger&&this.K===Y.K:!1};
h9.prototype.isExpired=function(){return(0,g.mJ)()-this.X>6E4};
h9.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.K};g.m(RXd,g.Ms);g.R=RXd.prototype;g.R.KF=function(){pK(this);this.player.l1("heartbeat");g.Ms.prototype.KF.call(this)};
g.R.onCueRangeEnter=function(){this.T=!0;MA(this,Ps(this))};
g.R.kA=function(Y){this.heartbeatParams=Y;MA(this,Ps(this))};
g.R.rZ=function(Y){var e;this.player.getPresentingPlayerType()!==8&&((e=this.K)==null?void 0:e.status)!=="UNPLAYABLE"&&(g.n(Y.state,2)||g.n(Y.state,64)?(pK(this),this.Y&&(this.T=!0,MA(this,Ps(this,!0)))):(g.n(Y.state,1)||g.n(Y.state,8))&&MA(this,Ps(this)))};
g.R.Sp=function(){this.player.getPresentingPlayerType()!==3&&MA(this,Ps(this))};
g.R.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.R.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.R.cD=function(Y){switch(Y){case 4:case 3:return!1}return!0};
g.R.Di=function(Y,e,K){Y={trigger:Y,reason:e};K&&(Y.serializedServerContext=K.additionalLoggingData);g.KV("heartbeatActionPlayerTransitioned",Y)};
g.R.aG=function(Y){var e="LICENSE",K=Qo7(Y);if(K)return K.reason||g.ns[e]||"";if(Y=Y.match(hX1))if(Y=Number(Y[1]))e=(e=v30[Y.toString()])?e:"LICENSE";return g.ns[e]||""};
g.R.Gc=function(){return!!this.offlineSlate&&this.offlineSlate.aq};
var hX1=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.PA("heartbeat",RXd);})(_yt_player);
